apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  region: us-east-1

availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 1 # Number of nodes
    minSize: 1 
    maxSize: 2 
    volumeSize: 20  # Size of the EBS volume attached to each node

