---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reader-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reader
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: reader
    spec:
      containers:
      - name: reader-container
        image: stevenextwave/reader:latest
        ports:
        - containerPort: 8084

